---
- name: Check the remote host uptime
  hosts: localhost
  tasks:
    - name: Execute the Uptime command over Command module
      command: "ls -la"
      register: lsla

    - debug:
        var: lsla
